=== amine-benhammada/amine-benhammada.github.io/tp1/foret.dtd
<!ELEMENT foret   (arbre | chemin)*>
<!ELEMENT chemin  (#PCDATA)>
<!ELEMENT arbre   (tronc)>
<!ELEMENT tronc   (branche*)>
<!ELEMENT branche (branche* | feuille)*>
<!ELEMENT feuille EMPTY>

=== amine-benhammada/amine-benhammada.github.io/tp1/bon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE foret SYSTEM "foret.dtd">
<foret>
  <arbre>
    <tronc>
      <branche>
        <feuille/>
      </branche>
    </tronc>
  </arbre>
  <arbre>
    <tronc/>
  </arbre>
  <arbre>
    <tronc>
      <branche>
        <feuille/>
      </branche>
    </tronc>
  </arbre>
</foret>

=== amine-benhammada/amine-benhammada.github.io/tp1/bon2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE foret SYSTEM "foret.dtd">
<foret>
  <arbre>
    <tronc>
      <branche>
        <feuille/>
      </branche>
    </tronc>
  </arbre>
  <arbre>
    <tronc>
      <branche>
        <branche>
          <branche>
            <feuille/>
          </branche>
        </branche>
      </branche>
    </tronc>
  </arbre>
</foret>
